version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: ./StyleMerge.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: NECXRcP/sdaNCCRpcoiyvutr0X9bc93mGyyXll2ouwCbwHGR5fXL+vXIAxwlz5gc
  skip_symbols: true
  on:
    APPVEYOR_REPO_TAG: true