version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.{build}
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: ./StyleMerge.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: NECXRcP/sdaNCCRpcoiyvutr0X9bc93mGyyXll2ouwCbwHGR5fXL+vXIAxwlz5gc
  skip_symbols: true
  on:
    APPVEYOR_REPO_TAG: true