version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: "Build the projects"
          command:
            dotnet build
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: "Run the Tests"
          command:
            dotnet test
  release:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: "Build the release artifact"
          command: |
            inferred_assembly_version="0.0.0.${CIRCLE_BUILD_NUM:-1}"
            version=$(echo "${CIRCLE_TAG:-$inferred_assembly_version}" | sed -E s/-.+$//)
            descriptive_version=${CIRCLE_TAG:-"$version-git-$CIRCLE_SHA1"}
            dotnet pack ./StyleMerge/StyleMerge.csproj -c Release -o ./artifacts /p:AssemblyVersion=$version /p:Version=$descriptive_version
      - run:
          name: "Push a new release"
          command: |
            if [[ -z "$PUBLIC_NUGET_PUBLISH" ]]; then echo '$PUBLIC_NUGET_PUBLISH is not set'; exit 1; fi
            dotnet nuget push $(ls ./artifacts/*.nupkg) -s https://www.nuget.org/ -k $PUBLIC_NUGET_PUBLISH
      - store_artifacts:
          path: artifacts

workflows:
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          context: postmark-library-builds
          requires:
            - build
            - test
          filters:
            tags:
              only: /^\d*\.\d*\.\d*/
            branches:
              ignore: /.*/