//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CssInliner.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Outputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Outputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CssInliner.Tests.Outputs", typeof(Outputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///a~~TEST_SELECTOR~~,.class1~~TEST_SELECTOR~~ { color: orange !important; }
        ///div~~TEST_SELECTOR~~ { font-family: Arial !important; }
        ///a~~TEST_SELECTOR~~ { font-size: 2em !important; }
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;a href=&quot;https://www.postmarkapp.com&quot;&gt;Postmark&lt;/a&gt;
        ///        &lt;span style=&quot;color: orange; font-family: Arial;&quot;&gt;Color should be red.&lt;/span&gt;
        ///        &lt;div style=&quot;background: red&quot;&gt;Color should be green.&lt;/div&gt;
        ///&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string CssInliner_Should_Handle_PseudoClasses {
            get {
                return ResourceManager.GetString("CssInliner_Should_Handle_PseudoClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;less-specific&quot; style=&quot;background:red&quot; id=&quot;main&quot;&gt;
        ///
        ///    &lt;/div&gt;
        ///    &lt;ul class=&quot;more-specific&quot; style=&quot;background:blue;font-family: Arial;&quot;&gt;&lt;/ul&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_InlinerShouldApplyStylesAccordingToSpecificityValues {
            get {
                return ResourceManager.GetString("Expected_InlinerShouldApplyStylesAccordingToSpecificityValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;selector1&quot; style=&quot;background:blue&quot;&gt;
        ///
        ///    &lt;/div&gt;
        ///    &lt;ul&gt;
        ///        &lt;li style=&quot;background:blue&quot;&gt;
        ///            This is an element.
        ///        &lt;/li&gt;
        ///    &lt;/ul&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_InlinerShouldApplyStylesForRulesWithMultipleSelectors {
            get {
                return ResourceManager.GetString("Expected_InlinerShouldApplyStylesForRulesWithMultipleSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;background-color: blue; width:100px;&quot; id=&quot;target&quot;&gt;This is the content.&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_InlinerShouldApplyStylesInDocumentOrder {
            get {
                return ResourceManager.GetString("Expected_InlinerShouldApplyStylesInDocumentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_InlinerShouldEliminateScriptBlocks {
            get {
                return ResourceManager.GetString("Expected_InlinerShouldEliminateScriptBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;background:purple&quot;&gt;
        ///
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_InlinerShouldEliminateStyleBlocksWhereAllRulesAreInlined {
            get {
                return ResourceManager.GetString("Expected_InlinerShouldEliminateStyleBlocksWhereAllRulesAreInlined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media (min-width: 768px) {
        ///            div {
        ///                background: red;
        ///            }
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;background:blue&quot;&gt;
        ///
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_InlinerShouldKeepMediaQueryStylesInStyleBlocks {
            get {
                return ResourceManager.GetString("Expected_InlinerShouldKeepMediaQueryStylesInStyleBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///@media (max-width: 700px){
        ///    body{
        ///        background: red;
        ///    }
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;link-block&quot; style=&quot;background: green;&quot;&gt;Hello, world.!&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Expected_Specificity_Ordering_Test {
            get {
                return ResourceManager.GetString("Expected_Specificity_Ordering_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string inliner_should_maintain_important_declaration {
            get {
                return ResourceManager.GetString("inliner_should_maintain_important_declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html style=&quot;font-family: Arial,&apos;Helvetica Neue&apos;,Helvetica,sans-serif; background: background-image:url(http://foobar.com);&quot;&gt;&lt;head&gt;
        ///
        ///&lt;/head&gt;&lt;body style=&quot;font-family: Arial,&apos;Helvetica Neue&apos;,Helvetica,sans-serif; background: background-image:url(http://foobar.com);&quot;&gt;
        ///
        ///&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string style_sheet_attributes_with_quotes_should_be_handled_properly {
            get {
                return ResourceManager.GetString("style_sheet_attributes_with_quotes_should_be_handled_properly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html style=&quot;color:purple&quot;&gt;
        ///&lt;head&gt;
        ///&lt;link href=&quot;./style.css&quot; type=&quot;text/css&quot; rel=&quot;Stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;color:purple&quot;&gt;
        ///&lt;span style=&quot;color:purple&quot;&gt;ASDF&lt;/span&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string universal_selector_doesnt_apply_to_head {
            get {
                return ResourceManager.GetString("universal_selector_doesnt_apply_to_head", resourceCulture);
            }
        }
    }
}
